# frozen_string_literal: true

module ExtrasDeCont

  class Parser
    @file: File

    def initialize: (File | String | Pathname | IO) -> void

    def parse_with: (Rules::Base) -> Array[Transaction]

    def text: -> String
  end
end
