# frozen_string_literal: true

module ExtrasDeCont
  class Transaction
    # The fields of the Struct
    attr_reader date: Date
    attr_reader description: String
    attr_reader amount: Float
    attr_reader currency: String

    # Constructor with keyword arguments (because you used keyword_init: true)
    def initialize: (date: Date, description: String, amount: Float, currency: String) -> void
  end
end