# frozen_string_literal: true

module ExtrasDeCont
  class Transaction
    attr_reader date: Date
    attr_reader description: String
    attr_reader amount: Numeric
    attr_reader currency: String
    attr_reader state: String?

    def initialize: (Date, String, Numeric, String, ?state: String?, ?deduplication_key: String?) -> void
    def deduplication_key: () -> String
    def reverted?: () -> bool
  end
end
